import loadUI from "./ui";
import grid from './modules/grid';
import Gameboard from "./modules/gameboard";
const Player = require('./modules/player');
const ship = require('./modules/ship');
import './styles.css';

//document.body.appendChild(loadUI());
const ui = loadUI();
const grid1 = grid.createGrid('player1');
const grid2 = grid.createGrid('player2');
ui.appendChild(grid1);
ui.appendChild(grid2);
document.body.appendChild(ui);
const board = new Gameboard('player1');
const p2board = new Gameboard('player2');
const battleship = new ship('battleship', 4);
const player2 = new Player('player2', false);
board.placeShip(battleship, battleship.length, 'vertical', 0, 0);
board.receiveAttack(1, 0);
player2.autoshoot(p2board);